development:
  sessions:
    default:
      database: kc_notifications_dev
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: kc_notifications_test
      hosts:
        - localhost:27017